from __future__ import annotations

import argparse
import asyncio
from typing import Any, Callable

import uvicorn
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.websocket import websocket_server
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Mount, Route, WebSocketRoute

from .server import create_mcp_app


async def _health(_: Any) -> JSONResponse:
    return JSONResponse({"ok": True})


def _build_mcp_ws_app(mcp_app) -> Callable[..., Any]:
    async def ws_app(scope, receive, send):
        async with mcp_app._lifespan_manager():
            async with websocket_server(scope, receive, send) as (read_stream, write_stream):
                await mcp_app._mcp_server.run(
                    read_stream,
                    write_stream,
                    mcp_app._mcp_server.create_initialization_options(
                        notification_options=NotificationOptions(tools_changed=True),
                    ),
                )

    return ws_app


def create_gateway_app(
    *,
    specs_path: str,
    max_rows: int,
    min_interval_seconds: float,
    transport: str = "streamable-http",
    path: str = "/mcp",
) -> Starlette:
    mcp_app = create_mcp_app(
        specs_path=specs_path,
        max_rows=max_rows,
        min_interval_seconds=min_interval_seconds,
    )

    mcp_http = mcp_app.http_app(path=path, transport=transport)
    ws_handler = _build_mcp_ws_app(mcp_app)

    routes = [
        Route("/healthz", _health),
        WebSocketRoute("/ws", ws_handler),
        Mount("/", app=mcp_http),
    ]
    return Starlette(routes=routes, lifespan=mcp_http.lifespan)


def cli_main() -> None:
    parser = argparse.ArgumentParser(description="HTTP/WS gateway for Tushare MCP.")
    parser.add_argument(
        "--specs",
        default="data/tushare_api_specs.json",
        help="Path to tushare_api_specs.json generated by scraper.",
    )
    parser.add_argument("--host", default="0.0.0.0", help="Bind host.")
    parser.add_argument("--port", type=int, default=8787, help="Bind port.")
    parser.add_argument(
        "--transport",
        default="streamable-http",
        choices=["http", "streamable-http", "sse"],
        help="MCP HTTP transport type.",
    )
    parser.add_argument("--path", default="/mcp", help="HTTP endpoint path.")
    parser.add_argument("--max-rows", type=int, default=100, help="Truncate rows.")
    parser.add_argument("--min-interval-seconds", type=float, default=0.35, help="Rate limit interval.")
    args = parser.parse_args()

    app = create_gateway_app(
        specs_path=args.specs,
        max_rows=args.max_rows,
        min_interval_seconds=args.min_interval_seconds,
        transport=args.transport,
        path=args.path,
    )

    uvicorn.run(app, host=args.host, port=args.port, log_level="info")


if __name__ == "__main__":
    cli_main()
